const COLOR_CLASS_GREEN = 'green'
const COLOR_CLASS_WHITE = 'white'
const COLOR_CLASS_BLACK = 'black'
const COLOR_CLASS_GRAY = 'gray'
const COLOR_CLASS_YELLOW = 'yellow'
const COLOR_CLASS_VIOLET = 'violet'
const COLOR_CLASS_BLUE = 'blue'
const COLOR_CLASS_RED = 'red'
const COLOR_CLASS_BROWN = 'brown'
const COLOR_CLASS_DARKBLUE = 'darkblue'
const COLOR_CLASS_SILVERGREY = 'silver-grey'
const COLOR_CLASS_ORANGE = 'orange'

export const ColorNames = {
  VERDE: COLOR_CLASS_GREEN,
  GREEN: COLOR_CLASS_GREEN,
  WHITE: COLOR_CLASS_WHITE,
  BLANCO: COLOR_CLASS_WHITE,
  NEGRO: COLOR_CLASS_BLACK,
  BLACK: COLOR_CLASS_BLACK,
  GRIS: COLOR_CLASS_GRAY,
  GRAY: COLOR_CLASS_GRAY,
  AMARILLO: COLOR_CLASS_YELLOW,
  YELLOW: COLOR_CLASS_YELLOW,
  VIOLET: COLOR_CLASS_VIOLET,
  VIOLETA: COLOR_CLASS_VIOLET,
  AZUL: COLOR_CLASS_BLUE,
  BLUE: COLOR_CLASS_BLUE,
  ROJO: COLOR_CLASS_RED,
  RED: COLOR_CLASS_RED,
  MARRON: COLOR_CLASS_BROWN,
  BROWN: COLOR_CLASS_BROWN,
  AZULOSCURO: COLOR_CLASS_DARKBLUE,
  DARKBLUE: COLOR_CLASS_DARKBLUE,
  SILVER: COLOR_CLASS_SILVERGREY,
  PLATA: COLOR_CLASS_SILVERGREY,
  ORANGE: COLOR_CLASS_ORANGE,
  NARANJA: COLOR_CLASS_ORANGE
}

export default { ColorNames }
